### ISSUE TITLE
Terminate script on compilation fail

### ISSUE THREAD

**Issue by dansteren** [xaves/cs236-test-runner#5]
**Problem:** When compiling the program it can encounter errors and not fully compile. However, regardless of whether the program compiles or not it still tries to run the executable. The result is either a crashing script (if the user has never compiled before) or the program continues to run the test on the old executable.

**Solution:** The script should check for errors in the compilation and terminate the script without trying to run the executable.

**Other Considerations:** If the script only outputs warnings then it should be fine to continue.

**Questions:**
- Should there be an option to continue even if the compilation failed?
- Should there be a verbose option that prints out all compilation output to the screen?
- Should there be a silent option that turns off all output?
- After compilation should we print the results of the compilation?
- Should we ask the user if they want to proceed with the execution?

**Comment by hi-im-michael** [comment]
Bump. This gives a lot of false positives since the program won't compile but you can still get false positives from tests that passed previously.

**Comment by dansteren** [comment]
@definitelynotmichael Thanks for the feedback. I hadn't fixed this one yet because I wasn't quite sure how. I'm looking at it right now and it looks like it might be easier than I thought. I'll implement it soon.
