### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by lewisjkl** [xaves/cs236-test-runner#7]
Would you be willing to include the source code for this project so that I could fork and make some modifications?

**Comment by dansteren** [comment]
@lewisjkl There isn't any "source code" per say. The whole project is the "test" file. "test" is a bash file and it was originally named test.sh. I just decided to drop the ".sh" to make it easier to run on the command line. So, if you want the source just open "test" in a text editor and you can read my code.

If you haven't coded in bash yet there's no better time to learn. You can checkout my cheat-sheet over at https://github.com/xaves/bash-cheat-sheet. It is a simple reference of the things I learned when I taught myself.

**Comment by lewisjkl** [comment]
Got it. I was thinking that maybe you wrote it in another language and compiled it into an executable file. Makes sense though, thanks for your help.
