### ISSUE TITLE
Handle different newline chars

### ISSUE THREAD

**Issue by TimWhiting** [xaves/cs236-test-runner#8]
So your test driver when it does the diff of the files it compares all whitespace - which because of Windows/unix and different ways that c++ outputs newlines can end up being different.

You can add the flag -Z on the diff to ignore whitespace at the end of the line. I've manually done this edit every time I download your test driver because I was getting this sort of misunderstanding.

**Comment by dansteren** [comment]
@TimWhiting thanks for the feedback.

If I change this will it still be in compliance with the TA's testdriver? I mean, what if a user produces output with 5 space characters at the end of the line? Should that pas too? I'm afraid that anything but an exact diff would mislead students and they would end up failing the TA's test driver. If you can verify for me that this will indeed fix the problem, I will add it in.

**Comment by TimWhiting** [comment]
The ta's testdriver does ignore differences in newline characters between unix and windows. Mine passed all of the testdrivers, though it didn't pass yours without the -Z option. I don't know how the ta's test driver works, but if they are using diff, then -Z seems like the only option they could be using to not ignore all whitespace, but ignore changes in newline formats..

**Comment by TimWhiting** [comment]
This is a link to the whitespace ignore options for diff.
http://www.gnu.org/software/diffutils/manual/html_node/White-Space.html#White-Space

**Comment by dansteren** [comment]
Awesome. Thanks for following up on that. I'll update it soon.
